CC=g++
CFLAGS=-Wno-deprecated
EXEC = Speedy

all:    
	$(CC) $(CFLAGS) main.cpp Entry.cpp GenericHeap.cpp ScenarioLoader.cpp Timer.cpp BucketPriorityQueue.cpp UnsortedPriorityQueue.cpp State.cpp -o $(EXEC)
